node {
    def app

    stage('Clone repository') {
        checkout scm
    }

    stage('Build image') {
        app = docker.build("hellonode:${env.BUILD_ID}")
    }

    stage('Test image') {
        app.inside {
            sh 'node --version'
        }
    }

    stage('Push image') {
        docker.withRegistry('http://localhost:6000') {
            app.push("${env.BUILD_NUMBER}")
            //app.push("latest")
        }
    }
}
