FROM grafana/grafana:latest

ENV GF_SECURITY_ADMIN_PASSWORD=secret
ENV GF_INSTALL_PLUGINS="grafana-clock-panel,grafana-simple-json-datasource"

ENV GF_AWS_PROFILES=default
ENV GF_AWS_default_REGION=eu-west-1
#ENV GF_AWS_default_ACCESS_KEY_ID=YOUR_ACCESS_KEY
#ENV GF_AWS_default_SECRET_ACCESS_KEY=YOUR_SECRET_KEY
